env:
  LC_ALL: en_US.UTF-8
jobs:
  publish:
    if: github.repository == 'line/centraldogma'
    name: Publish final artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      id: setup-jdk-17
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build with Gradle
      run: './gradlew --no-daemon --stacktrace build -PflakyTests=false

        '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USER_NAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
      name: Publish and close repository
      run: './gradlew --no-daemon --stacktrace --max-workers=1 publish closeAndReleaseStagingRepository

        '
    - continue-on-error: true
      name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        asset_name: ${{ github.ref_name }}.tgz
        file: dist/build/${{ github.ref_name }}.tgz
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
name: Publish final artifacts to Maven Central repository
on:
  repository_dispatch:
    types: trigger-ga___publish-release.yml
