env:
  IMAGE_NAME: ${{ github.repository }}
  LC_ALL: en_US.UTF-8
  REGISTRY: ghcr.io
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out the repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build Docker image
      run: ./gradlew :dist:docker --stacktrace
      shell: bash
    - continue-on-error: true
      id: release-version
      name: Extract release version
      uses: actions/github-script@v4
      with:
        result-encoding: string
        script: 'const version = context.ref.replace(/.*centraldogma-/, '''')

          console.log(''Release version: '' + version)

          return version

          '
    - continue-on-error: true
      name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Push Docker image
      run: 'docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.release-version.outputs.result
        }}

        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

        '
      shell: bash
name: Publish Docker image
on:
  repository_dispatch:
    types: trigger-ga___publish-docker.yml
