jobs:
  update-armeria-version:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Wait for Armeria artifacts to be available
      uses: nev7n/wait_for_response@v1
      with:
        interval: 60000
        responseCode: 200
        timeout: 18000000
        url: https://repo.maven.apache.org/maven2/com/linecorp/armeria/armeria-bom/${{
          inputs.armeria_version }}/armeria-bom-${{ inputs.armeria_version }}.pom
    - continue-on-error: true
      name: Update Armeria version to ${{ inputs.armeria_version }}
      run: 'sed -i "s/armeria = \".*\"/armeria = \"${{ inputs.armeria_version }}\"/"
        dependencies.toml

        '
    - continue-on-error: true
      id: import_gpg
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSWORD }}
    - continue-on-error: true
      name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: 'dependencies.toml

          '
        author: Meri Kim <dl_armeria@linecorp.com>
        body: ''
        branch: update-armeria-version
        commit-message: Update Armeria version to ${{ inputs.armeria_version }}
        committer: Meri Kim <dl_armeria@linecorp.com>
        delete-branch: true
        label: dependencies
        title: Update Armeria version to ${{ inputs.armeria_version }}
        token: ${{ secrets.GH_ACCESS_TOKEN }}
name: Update Armeria version
on:
  repository_dispatch:
    types: trigger-ga___update-armeria-version.yml
